CREATE TABLE DIRECTOR
(
    ID   UUID    NOT NULL,
    NAME VARCHAR NOT NULL,
    CONSTRAINT DIRECTOR_PK PRIMARY KEY (ID)
);

CREATE TABLE MOVIE
(
    ID           UUID        NOT NULL,
    TITLE        VARCHAR     NOT NULL,
    GENRE        VARCHAR     NOT NULL,
    DIRECTOR_ID  UUID        NOT NULL,
    RELEASE_DATE TIMESTAMPTZ NOT NULL,
    CONSTRAINT MOVIE_PK PRIMARY KEY (ID),
    FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTOR (ID)
);

CREATE INDEX IDX_MOVIE_GENRE ON MOVIE (GENRE);

CREATE TABLE USERS
(
    ID       UUID    NOT NULL,
    USERNAME VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID)
);
